Repository alcosi/twinfaces, pull requests merged in 2025-03, with the labels that each got.

#245 [TWINFACES-484] feat: implement dynamic and customizable login page functional
  .env
  .env.example
  public/onshelves/favicon.png
  public/twinfaces/favicon.png
  src/app/layout.tsx
  src/app/page.tsx
  src/screens/home/index.ts
  src/screens/login/index.ts
  src/screens/login/login.tsx
  src/shared/config/config.ts
  src/shared/config/context-provider.tsx
  src/shared/config/index.ts
  src/shared/config/types.ts
Labels: High

#249 TWINFACES-489 :sparkles: Implement <TwinsTable />
  public/onshelves/ons-product-items.json
  src/app/design-system/components/ui-section.tsx
  src/app/design-system/layout.tsx
  src/app/design-system/page.tsx
  src/app/design-system/tabs/tables.tsx
  src/app/workspace/twinclass/[twinClassId]/views/twin-class-general.tsx
  src/entities/twin-class/api/hooks/use-fetch-twin-class-by-id.ts
  src/entities/twin-class/api/types.ts
  src/entities/twin-class/contexts/context.tsx
  src/entities/twin-class/libs/hooks/use-filters.ts
  src/entities/twin-class/libs/hooks/use-select-adapter.ts
  src/entities/twin/api/api-service.ts
  src/entities/twin/api/hooks/useSearchV3.ts
  src/entities/twin/api/types.ts
  src/entities/twin/libs/hooks/useFilters.ts
  src/entities/twinFlowSchema/components/resource-link/resource-link.tsx
  src/features/factory/context-provider.tsx
  src/screens/twinClasses/form-fields.tsx
  src/screens/twins/twins.tsx
  src/shared/api/generated/schema.d.ts
  src/shared/config/config.ts
  src/shared/config/types.ts
  src/shared/libs/types/filters.ts
  src/widgets/crud-data-table/crud-data-table.tsx
  src/widgets/crud-data-table/header/filters-popover.tsx
  src/widgets/tables/index.ts
  src/widgets/tables/twins/form-fields.tsx
  src/widgets/tables/twins/index.ts
  src/widgets/tables/twins/twins.tsx
  src/widgets/tables/twins/use-twin-form-fields.ts
Labels: High

#251 TWINFACES-489 :ambulance: Allow selecting twin-class on design-system
  src/app/design-system/components/ui-section.tsx
  src/app/design-system/tabs/tables.tsx
  src/widgets/tables/twins/twins.tsx
Labels: High

#247 [TWINFACES-488] page twin tab subordinate twins tabs
  src/app/workspace/twins/[twinId]/layout.tsx
  src/app/workspace/twins/[twinId]/page.tsx
  src/app/workspace/twins/[twinId]/twin-context.tsx
  src/app/workspace/twins/[twinId]/views/twin-comments.tsx
  src/app/workspace/twins/[twinId]/views/twin-fields.tsx
  src/app/workspace/twins/[twinId]/views/twin-general.tsx
  src/app/workspace/twins/[twinId]/views/twin-history.tsx
  src/app/workspace/twins/[twinId]/views/twin-links.tsx
  src/entities/twin-class/api/hooks/use-twin-class-search-v1.ts
  src/entities/twin-class/api/types.ts
  src/entities/twin/api/api-service.ts
  src/entities/twin/api/hooks/index.ts
  src/entities/twin/api/hooks/use-fetch-by-id-v2.ts
  src/entities/twin/api/hooks/useFetchByIdV2.ts
  src/entities/twin/api/types.ts
  src/features/twin/context-provider.tsx
  src/features/twin/index.ts
  src/widgets/layout/tabs-layout/layout.tsx
Labels: High

#253 [TWINFACES-489] Refactor <TwinsTable />
  src/app/workspace/twins/[twinId]/page.tsx
  src/entities/twin-class-field/api/api-service.ts
  src/entities/twin-class-field/api/types.ts
  src/entities/twin-class-field/libs/hooks/use-filters.ts
  src/entities/twin/api/types.ts
  src/shared/api/generated/schema.d.ts
  src/shared/libs/helpers.ts
  src/shared/ui/combobox/hooks/use-combobox.tsx
  src/widgets/crud-data-table/crud-data-table.tsx
  src/widgets/crud-data-table/header/header.tsx
  src/widgets/tables/twin-class-fields/twin-class-fields.tsx
  src/widgets/tables/twins/twins.tsx
Labels: High

#248 [TWINFACES-487] feat: implement box and shopping bag icon components
  src/app/design-system/page.tsx
  src/app/design-system/tabs/icons.tsx
  src/shared/ui/icons/box-icon.tsx
  src/shared/ui/icons/index.ts
  src/shared/ui/icons/shopping-bag-icon.tsx
  src/shared/ui/icons/tier-icon.tsx
  src/widgets/layout/sidebar-layout/sidebar/constants.ts
Labels: Medium

#244 [TWINFACES-477] modal permission grant twin role create
  src/entities/permission/api/api-service.ts
  src/entities/permission/api/hooks/index.ts
  src/entities/permission/api/hooks/use-create-permission-grant-twin-role.ts
  src/entities/permission/api/hooks/use-create-permission-grant-user-group.ts
  src/entities/permission/api/hooks/use-create-permission-grant-user.ts
  src/entities/permission/api/types.ts
  src/entities/permission/libs/constants.ts
  src/entities/twin-class/libs/hooks/use-select-adapter.ts
  src/entities/twin-role/api/api-service.ts
  src/entities/twin-role/api/hooks/index.ts
  src/entities/twin-role/api/hooks/use-search-twin-roles.ts
  src/entities/twin-role/api/index.ts
  src/entities/twin-role/api/types.ts
  src/entities/twin-role/index.ts
  src/entities/twin-role/libs/constants.ts
  src/entities/twin-role/libs/helpers.ts
  src/entities/twin-role/libs/index.ts
  src/entities/twin-role/libs/types.ts
  src/entities/twinRole/api/hooks/index.ts
  src/entities/twinRole/libs/index.ts
  src/features/api/context/private-context-provider.tsx
  src/screens/permission/views/grant-section/twin-role-table/form-fields.tsx
  src/screens/permission/views/grant-section/twin-role-table/twin-role-table.tsx
Labels: Medium

#230 [TWINFACES-330] added tab pipeline step general
  src/app/workspace/pipeline-steps/[stepId]/layout.tsx
  src/app/workspace/pipeline-steps/[stepId]/page.tsx
  src/entities/factory-pipeline-step/api/api-service.ts
  src/entities/factory-pipeline-step/api/hooks/index.ts
  src/entities/factory-pipeline-step/api/hooks/use-fetch-by-id.ts
  src/entities/factory-pipeline-step/api/hooks/use-search-v1.ts
  src/entities/factory-pipeline-step/api/hooks/use-update.ts
  src/entities/factory-pipeline-step/api/index.ts
  src/entities/factory-pipeline-step/api/types.ts
  src/entities/factory-pipeline-step/libs/hooks/index.ts
  src/features/pipeline-step/context-provider.tsx
  src/features/pipeline-step/index.ts
  src/screens/pipeline-step/index.ts
  src/screens/pipeline-step/pipeline-step.tsx
  src/screens/pipeline-step/views/general.tsx
  src/screens/pipeline-step/views/index.ts
Labels: Medium

#260 [TWINFACES-497] replaced twinClassIdList with twinClassIdMap in the filter for statuses
  src/entities/domain/api/types.ts
  src/entities/twin-status/api/types.ts
  src/entities/twin-status/libs/hooks/use-filters.ts
  src/entities/twin-status/libs/hooks/use-select-adapter.tsx
  src/shared/api/generated/schema.d.ts
  src/shared/config/types.ts
  src/widgets/tables/twin-class-statuses/twin-class-statuses.tsx
Labels: Blocked

#243 [TWINFACES-385] added table tiers
  src/app/workspace/tiers/page.tsx
  src/components/auto-field.tsx
  src/components/form-fields/index.ts
  src/components/form-fields/range/index.ts
  src/components/form-fields/range/number-range-form-field.tsx
  src/entities/tier/api/api-service.ts
  src/entities/tier/api/hooks/index.ts
  src/entities/tier/api/hooks/use-search.ts
  src/entities/tier/api/index.ts
  src/entities/tier/api/types.ts
  src/entities/tier/index.ts
  src/entities/tier/libs/helpers.ts
  src/entities/tier/libs/hooks/index.ts
  src/entities/tier/libs/hooks/use-filters.ts
  src/entities/tier/libs/index.ts
  src/entities/twin-class-schema/api/index.ts
  src/entities/twin-class-schema/api/types.ts
  src/entities/twin-class-schema/components/index.ts
  src/entities/twin-class-schema/components/resource-link/index.ts
  src/entities/twin-class-schema/components/resource-link/resource-link.tsx
  src/entities/twin-class-schema/components/resource-link/tooltip.tsx
  src/entities/twin-class-schema/components/twin-class-schema-icon.tsx
  src/entities/twin-class-schema/index.ts
  src/entities/twinFlowSchema/api/types.ts
  src/features/api/context/private-context-provider.tsx
  src/screens/tiers/index.ts
  src/screens/tiers/tiers.tsx
  src/widgets/tables/tiers/index.ts
  src/widgets/tables/tiers/tiers.tsx
Labels: Low

#261 [TWINFACES-494] twin status transition
  src/entities/twin-flow-transition/api/api-service.ts
  src/entities/twin-flow-transition/api/hooks/index.ts
  src/entities/twin-flow-transition/api/hooks/use-create-twin-flow-transition.ts
  src/entities/twin-flow-transition/api/hooks/use-fetch-by-id-v1.ts
  src/entities/twin-flow-transition/api/hooks/use-perform-transition.ts
  src/entities/twin-flow-transition/api/hooks/use-search-triggers.ts
  src/entities/twin-flow-transition/api/hooks/use-search-v1.ts
  src/entities/twin-flow-transition/api/hooks/use-search-validator-rules.ts
  src/entities/twin-flow-transition/api/types.ts
  src/entities/twin/api/api-service.ts
  src/entities/twin/libs/helpers.ts
  src/features/transition-performer/index.ts
  src/features/transition-performer/transition-performer.tsx
  src/widgets/tables/twins/twins.tsx
Labels: High

#265 [TWINFACES-0] fix filters twinflow transition
  src/entities/twin-flow/api/types.ts
  src/entities/twin-flow/libs/hooks/useFilters.ts
  src/features/twinFlow/context-provider.tsx
  src/screens/twinClassTwinFlows/twinClassTwinFlows.tsx
Labels: High

#259 [TWINFACES-311] page factory tab flow
  src/app/core/pipelines/page.tsx
  src/entities/factory-branch/libs/hooks/use-filters.ts
  src/entities/factory-multiplier/api/hooks/use-create.ts
  src/entities/factory-multiplier/libs/hooks/use-filters.ts
  src/entities/factory-pipeline-step/api/api-service.ts
  src/entities/factory-pipeline-step/api/hooks/index.ts
  src/entities/factory-pipeline-step/api/hooks/use-create.ts
  src/entities/factory-pipeline-step/api/index.ts
  src/entities/factory-pipeline-step/api/types.ts
  src/entities/factory-pipeline-step/libs/index.ts
  src/entities/factory-pipeline-step/libs/schema.ts
  src/entities/factory-pipeline/api/api-service.ts
  src/entities/factory-pipeline/api/hooks/index.ts
  src/entities/factory-pipeline/api/hooks/use-create.ts
  src/entities/factory-pipeline/api/hooks/use-search-v1.ts
  src/entities/factory-pipeline/api/types.ts
  src/entities/factory-pipeline/libs/hooks/use-factory-pipeline-select-adapter.ts
  src/entities/factory-pipeline/libs/hooks/use-filters.ts
  src/entities/factory-pipeline/libs/index.ts
  src/entities/factory-pipeline/libs/schemas.ts
  src/screens/factory-branches/factory-branches.tsx
  src/screens/factory-multipliers/factory-multipliers.tsx
  src/screens/factory-pipelines/factory-pipelines.tsx
  src/screens/factory/factory.tsx
  src/screens/factory/views/factory-flow.tsx
  src/screens/factory/views/index.ts
  src/shared/ui/accordion.tsx
  src/widgets/tables/factory-branches/factory-branches.tsx
  src/widgets/tables/factory-branches/form-fields.tsx
  src/widgets/tables/factory-branches/index.ts
  src/widgets/tables/factory-multipliers/factory-multipliers.tsx
  src/widgets/tables/factory-multipliers/form-fields.tsx
  src/widgets/tables/factory-multipliers/index.ts
  src/widgets/tables/factory-pipelines/factory-pipelines.tsx
  src/widgets/tables/factory-pipelines/form-fields.tsx
  src/widgets/tables/factory-pipelines/index.ts
  src/widgets/tables/index.ts
  src/widgets/tables/pipeline-steps/form-fields.tsx
  src/widgets/tables/pipeline-steps/pipeline-steps.tsx
Labels: Medium
