Repository alcosi/twinfaces, pull requests merged in 2025-04, with the labels that each got.

#283 [TWINFACES-507] Fix CrudDataTableHeader layout overflow on horizontal scroll
  src/widgets/faces/components/widget-layout-renderer.tsx
Labels: 🐛 bug

#281 [TWINFACES-502] add thumbnail slider in [face twiget] TW001
  src/app/api/mime-type/route.ts
  src/app/globals.css
  src/entities/twin/server/api/types.ts
  src/shared/libs/constants.ts
  src/shared/ui/caption.tsx
  src/shared/ui/icons/file-question-icon.tsx
  src/shared/ui/icons/index.ts
  src/shared/ui/icons/pdf-icon.tsx
  src/shared/ui/index.ts
  src/shared/ui/sliders/index.ts
  src/shared/ui/sliders/slide-view.tsx
  src/shared/ui/sliders/slot-slider/index.ts
  src/shared/ui/sliders/slot-slider/slot-slider.tsx
  src/shared/ui/sliders/slot-slider/views/image.tsx
  src/shared/ui/sliders/slot-slider/views/pdf.tsx
  src/shared/ui/sliders/slot-slider/views/unknown.tsx
  src/shared/ui/sliders/slot-slider/views/video.tsx
  src/widgets/faces/widgets/views/tw001.tsx
  tailwind.config.ts
Labels: 🔴 High

#284 [TWINFACES-509] refactor: change theme option selection from text to icons
  src/components/theme-toggle.tsx
Labels: 🟢 Low

#280 [TWINFACES-110] applied a single background color to the tooltip
  scripts/create_entity.sh
  src/entities/comment/components/resource-link/tooltip.tsx
  src/entities/comment/libs/constants.ts
  src/entities/comment/libs/index.ts
  src/entities/featurer/components/resource-link/tooltip.tsx
  src/entities/featurer/libs/constants.ts
  src/entities/twin-class-field/components/resource-link/tooltip.tsx
  src/entities/twin-class-field/libs/constants.ts
  src/entities/twin-class-field/libs/index.ts
  src/entities/twin-flow-transition/components/resource-link/tooltip.tsx
  src/entities/twin-flow-transition/libs/constants.ts
  src/entities/twin-flow/components/resource-link/tooltip.tsx
  src/entities/twin-flow/libs/constants.ts
  src/entities/twin-flow/libs/index.ts
  src/entities/twin-status/components/resource-link/tooltip.tsx
  src/entities/twin-status/libs/constants.ts
  src/entities/twinFlowSchema/components/resource-link/tooltip.tsx
  src/entities/twinFlowSchema/libs/constants.ts
  src/entities/twinFlowSchema/libs/index.ts
  src/entities/user-group/components/resource-link/tooltip.tsx
  src/entities/user-group/libs/constants.ts
  src/entities/user-group/libs/index.ts
  src/shared/ui/resource-link/resource-link.tsx
  src/shared/ui/resource-link/tooltip.tsx
Labels: 🟢 Low

#238 [TWINFACES-329] added table factory erasers
  src/app/core/erasers/[eraserId]/layout.tsx
  src/app/core/erasers/[eraserId]/page.tsx
  src/app/core/erasers/page.tsx
  src/entities/factory-eraser/api/api-service.ts
  src/entities/factory-eraser/api/hooks/index.ts
  src/entities/factory-eraser/api/hooks/use-fetch-by-id.ts
  src/entities/factory-eraser/api/hooks/use-search.ts
  src/entities/factory-eraser/api/hooks/use-update.ts
  src/entities/factory-eraser/api/index.ts
  src/entities/factory-eraser/api/types.ts
  src/entities/factory-eraser/index.ts
  src/entities/factory-eraser/libs/constans.ts
  src/entities/factory-eraser/libs/helpers.ts
  src/entities/factory-eraser/libs/hooks/index.ts
  src/entities/factory-eraser/libs/hooks/use-filters.ts
  src/entities/factory-eraser/libs/index.ts
  src/features/api/context/private-context-provider.tsx
  src/features/factory-eraser/context-provider.tsx
  src/features/factory-eraser/index.ts
  src/screens/factory-eraser/factory-eraser.tsx
  src/screens/factory-eraser/index.ts
  src/screens/factory-eraser/views/factory-eraser-general.tsx
  src/screens/factory-eraser/views/index.ts
  src/screens/factory-erasers/factory-erasers.tsx
  src/screens/factory-erasers/index.ts
  src/screens/permission/views/general-section.tsx
Labels: 🟠 Medium

#298 [TWINFACES-520] added TW005
  src/entities/face/api/actions/tw.ts
  src/entities/face/api/types.ts
  src/entities/twin-flow-transition/api/types.ts
  src/features/twin-flow-transition/transition-perform-button.tsx
  src/features/twin/ui/view-as-admin.tsx
  src/shared/api/generated/schema.d.ts
  src/widgets/faces/components/widget-layout-renderer.tsx
  src/widgets/faces/widgets/renderer.tsx
  src/widgets/faces/widgets/views/index.ts
  src/widgets/faces/widgets/views/tw005.tsx
Labels: 🔴 High

#301 [TWINFACES-269] update input field transition alias single
  src/entities/twin-flow-transition/libs/constants.ts
  src/entities/twin-flow-transition/libs/hooks/use-alias-select-adapter.ts
  src/screens/twin/views/twin-fields.tsx
  src/shared/libs/constants.ts
  src/widgets/tables/twin-flow-transitions/form-fields.tsx
Labels: 🔴 High

#242 [TWINFACES-483] Switch component, confirm dialogs
  package-lock.json
  package.json
  src/app/core/twinclass/[twinClassId]/views/twin-class-general.tsx
  src/app/design-system/page.tsx
  src/app/design-system/tabs/action-dialogs.tsx
  src/app/design-system/tabs/input-fields.tsx
  src/features/ui/action-dialogs/confirm-dialog.tsx
  src/features/ui/action-dialogs/context.tsx
  src/features/ui/action-dialogs/index.ts
  src/features/ui/action-dialogs/use-action-dialogs.ts
  src/shared/libs/utils/index.ts
  src/shared/libs/utils/string.ts
  src/shared/libs/utils/uuid.ts
  src/shared/ui/switch.tsx
  src/widgets/layout/providers/private.tsx
  src/widgets/layout/providers/public.tsx
Labels: 🟢 Low
